### ISSUE TITLE
Items undefined for tennis_courts_keypoints_training.ipynb

### ISSUE THREAD

**Issue by kinfungchan** [abdullahtarek/tennis_analysis#2]
Hi, Love the YouTube Channel. When Creating the Torch Data Set, there seems to be a bug when creating the np.array for the Keys with kps. In particular kps = np.array(items['kps']).flatten() in the __getitem__(self, idx) method. Thanks!

**Comment by Tennisee-data** [comment]
hello, just take the s out of items as item is defined not items...
